export const UPDATE_INGREDIENTS = "UPDATE_INGREDIENTS";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_BUN_INGREDIENT = "SET_BUN_INGREDIENT";
export const SORT_INGREDIENTS = "SORT_INGREDIENTS";
